version: '3'

networks:
  camunda_network:
    external: true

services:
  openldap:
    container_name: ldap
    image: bitnami/openldap:2
    ports:
      - '1389:1389'
      - '1636:1636'
    environment:
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_ADMIN_PASSWORD=adminpassword
      - LDAP_USERS=user01,user02
      - LDAP_PASSWORDS=password1,password2
    volumes:
      - 'openldap_data:/bitnami/openldap'
    networks:
      - camunda_network

volumes:
  openldap_data:
    driver: local
